
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";
const ADDPROGRAM= 'ADDPROGRAM'
const FETCH_ALL_PROGRAMS= 'FETCH_ALL_PROGRAMS'
const FETCH_SINGLE_PROGRAM= 'FETCH_SINGLE_PROGRAM'
const UPDATE_USER= 'UPDATE_USER'
const GET_USER= 'GET_USER'
const UPLOAD_PHOTO= 'UPLOAD_PHOTO'

export {
    FETCH_SINGLE_PROGRAM,
    AUTHENTICATION,
    LOGOUT,
    ADDPROGRAM,
    FETCH_ALL_PROGRAMS,
    UPDATE_USER,
    GET_USER,
    UPLOAD_PHOTO
}